// <auto-generated />
namespace AutoPartsMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeDescriptions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeDescriptions));
        
        string IMigrationMetadata.Id
        {
            get { return "201711231439077_removeDescriptions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
