//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPartsMVC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoPartsMVC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави в количката.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to общите условия на сайта.
        /// </summary>
        public static string Agreement {
            get {
                return ResourceManager.GetString("Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Български.
        /// </summary>
        public static string Bulgarian {
            get {
                return ResourceManager.GetString("Bulgarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количка.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поръчай.
        /// </summary>
        public static string CartFinishOrder {
            get {
                return ResourceManager.GetString("CartFinishOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string CartPriceTitle {
            get {
                return ResourceManager.GetString("CartPriceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукт.
        /// </summary>
        public static string CartProductTitle {
            get {
                return ResourceManager.GetString("CartProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брой.
        /// </summary>
        public static string CartQuantity {
            get {
                return ResourceManager.GetString("CartQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общо.
        /// </summary>
        public static string CartWholePrice {
            get {
                return ResourceManager.GetString("CartWholePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог.
        /// </summary>
        public static string Catalogue {
            get {
                return ResourceManager.GetString("Catalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промени паролата си.
        /// </summary>
        public static string ChangePass {
            get {
                return ResourceManager.GetString("ChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Град.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string ContactAddress {
            get {
                return ResourceManager.GetString("ContactAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефони.
        /// </summary>
        public static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакти.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продължи с пазаруването.
        /// </summary>
        public static string ContinueShopping {
            get {
                return ResourceManager.GetString("ContinueShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Държава.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to лв..
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доставката на поръчката зависи от тарифата на избраната от вас фирма доставчик..
        /// </summary>
        public static string DeliveryTerms {
            get {
                return ResourceManager.GetString("DeliveryTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Английски.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string FamilyName {
            get {
                return ResourceManager.GetString("FamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крайна цена.
        /// </summary>
        public static string FinalPrice {
            get {
                return ResourceManager.GetString("FinalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Намерете ни бързо и лесно.
        /// </summary>
        public static string FindUs {
            get {
                return ResourceManager.GetString("FindUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Безплатна доставка на всички продукти с български пощи.
        /// </summary>
        public static string FreeBGPosts {
            get {
                return ResourceManager.GetString("FreeBGPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съгласявам се с.
        /// </summary>
        public static string IAgree {
            get {
                return ResourceManager.GetString("IAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Език.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разбери повече.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Влез.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Излез.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Никога няма да използваме вашите данни за неправилни неща..
        /// </summary>
        public static string NeverGonnaUseYourData {
            get {
                return ResourceManager.GetString("NeverGonnaUseYourData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Офис на доставчик.
        /// </summary>
        public static string OfficeAddress {
            get {
                return ResourceManager.GetString("OfficeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поръчка.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начин на плащане.
        /// </summary>
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание на продукта.
        /// </summary>
        public static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име на продукта.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снимка.
        /// </summary>
        public static string ProductPicture {
            get {
                return ResourceManager.GetString("ProductPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профил.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПРОМО!.
        /// </summary>
        public static string Promo {
            get {
                return ResourceManager.GetString("Promo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промоции.
        /// </summary>
        public static string Promos {
            get {
                return ResourceManager.GetString("Promos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомни ме?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специални оферти.
        /// </summary>
        public static string SpecialOffers {
            get {
                return ResourceManager.GetString("SpecialOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпрати.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Публикувай авточасти тук!.
        /// </summary>
        public static string SubmitPartsHere {
            get {
                return ResourceManager.GetString("SubmitPartsHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравления! Вие изпратихте своята поръчка! Очаквайте скорошно обаждане от нас!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разгледай.
        /// </summary>
        public static string TakeALook {
            get {
                return ResourceManager.GetString("TakeALook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Условия за доставка.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До офис на.
        /// </summary>
        public static string ToOffice {
            get {
                return ResourceManager.GetString("ToOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Твоите поръчки.
        /// </summary>
        public static string YourOrders {
            get {
                return ResourceManager.GetString("YourOrders", resourceCulture);
            }
        }
    }
}
